---
repos:
  - repo: git@github.com:pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-case-conflict
      - id: fix-byte-order-marker
      - id: check-symlinks
      - id: forbid-new-submodules
      - id: trailing-whitespace
      - id: fix-encoding-pragma
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
