[tox]
minversion = 1.8
envlist = py{311,312,313}-ansible{12,13}
skipsdist = true

[testenv]
passenv = *
deps =
    -rrequirements.txt
    ansible12: ansible>=12.0,<13.0
    ansible13: ansible>=13.0,<14.0
commands =
    pip list
    molecule --version
    ansible --version
    ansible-lint --version
    molecule test

[gh-actions]
python =
    3.11: py311
    3.12: py312
    3.13: py313
[gh-actions:env]
ANSIBLE =
  12: ansible12
  13: ansible13
