[tox]
minversion = 1.8
envlist = py{311,312,313}-ansible{13}
skipsdist = true

[testenv]
passenv = *
deps =
    -rrequirements.txt
    ansible13: ansible>=13.0,<14.0
commands =
    pip list
    molecule --version
    ansible --version
    ansible-lint --version
    molecule test

[gh-actions]
python =
    3.12: py312
    3.13: py313
    3.14: py314
[gh-actions:env]
ANSIBLE =
  13: ansible13
