---
# tasks file for rpi-boot-config
- name: "adjust /boot/config.txt"
  lineinfile: line='{{ item.key }}={{ item.value }}'
    dest=/boot/config.txt
    regexp="^{{ item.key }}="
  with_dict: '{{ boot_config }}'
  register: _boot_config

- name: restart machine
  shell: sleep 2 && shutdown -r now "/boot/config.txt config changed"
  async: 1
  poll: 0
  ignore_errors: true
  when: _boot_config.changed

- name: waiting for machine to come back
  local_action: wait_for port=22 host="{{ ansible_host }}" delay=20 timeout=120
  become: false
  when: _boot_config.changed
