---
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint --exclude molecule
platforms:
  # since we don't need to test against the OS, one is enough here
  - name: rpibootconfig-debian-12-bookworm
    image: debian:bookworm
    dockerfile: ../common/Dockerfile.j2
provisioner:
  name: ansible
  config_options:
    defaults:
      roles_path: "$ANSIBLE_ROLES_PATH:$MOLECULE_PROJECT_DIRECTORY/..:$HOME/.ansible/roles"
  env:
    # https://github.com/ansible-community/molecule-plugins/
    # until molecule-docker has a new release, we need to do this:
    ANSIBLE_ALLOW_BROKEN_CONDITIONALS: "True"
scenario:
  name: default
verifier:
  name: testinfra
