---
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint --exclude molecule
platforms:
  - name: rpibootconfig-debian-11-bullseye
    image: debian:bullseye
  - name: rpibootconfig-debian-buster
    image: debian:buster
  - name: rpibootconfig-debian-stretch
    image: debian:stretch
  - name: rpibootconfig-debian-jessie
    image: debian:jessie
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: testinfra
